inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true

Layout/AlignParameters:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Exclude:
    - 'test/fake_jobs.rb'

Style/EmptyMethod:
  Exclude:
    - 'test/fake_jobs.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'Appraisals'
    - 'Gemfile'
    - 'Rakefile'
    - 'gemfiles/*'
    - 'resque_solo.gemspec'

Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiterals:
  EnforcedStyle: double_quotes
